application: html5playbook
version: canary-v3
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: img

- url: /samples
  static_dir: samples

- url: /static
  static_dir: static

- url: /
  static_files: studio.html
  upload: studio.html

# Server appropriate mimetype for certain static content.
- url: /samples/(.*\.manifest)
  static_files: samples/\1
  mime_type: text/cache-manifest
  upload: samples/(.*\.manifest)

- url: /samples/(.*\.mp4)
  static_files: samples/\1
  mime_type: video/mp4
  upload: samples/(.*\.mp4)

- url: /samples/(.*\.webm)
  static_files: samples/\1
  mime_type: video/webm
  upload: samples/(.*\.webm)

- url: /samples/(.*\.ogv)
  static_files: samples/\1
  mime_type: video/ogg
  upload: samples/(.*\.ogv)

- url: /samples/(.*\.(ogg|oga))
  static_files: samples/\1
  mime_type: audio/ogg
  upload: samples/(.*\.(ogg|oga))
