application: html5rocks
version: 5
runtime: python
api_version: 1

default_expiration: "30d"

handlers:

- url: /google75906d613a2a09ba.html
  static_files: static/google75906d613a2a09ba.html
  upload: static/google75906d613a2a09ba.html

- url: /tutorials.*(\.html|/)
  script: main.py

# Server appropriate mimetype for certain static content.
- url: /tutorials/(.*\.manifest)
  static_files: content/tutorials/\1
  mime_type: text/cache-manifest
  upload: content/tutorials/(.*\.manifest)

- url: /tutorials/(.*\.crx)
  static_files: content/tutorials/\1
  mime_type: application/x-chrome-extension
  upload: content/tutorials/(.*\.crx)

- url: /tutorials/(.*\.mp4)
  static_files: content/tutorials/\1
  mime_type: video/mp4
  upload: content/tutorials/(.*\.mp4)

- url: /tutorials/(.*\.webm)
  static_files: content/tutorials/\1
  mime_type: video/webm
  upload: content/tutorials/(.*\.webm)

- url: /tutorials/(.*\.ogv)
  static_files: content/tutorials/\1
  mime_type: video/ogg
  upload: content/tutorials/(.*\.ogv)

- url: /tutorials/(.*\.(ogg|oga))
  static_files: content/tutorials/\1
  mime_type: audio/ogg
  upload: content/tutorials/(.*\.(ogg|oga))

- url: /tutorials/(.*\.mp3)
  static_files: content/tutorials/\1
  mime_type: audio/mpeg
  upload: content/tutorials/(.*\.mp3)

# Catch other static content.
- url: /tutorials/(.*\.(gif|swf|mp3|css|js|png|jpeg|jpg|svg|ogm|fla))
  static_files: content/tutorials/\1
  upload: content/tutorials/(.*\.(gif|swf|mp3|css|js|png|jpeg|jpg|svg|ogm|fla))

# Anything under /static will automatically be considered static.
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: .*
  script: main.py
