application: html5rocks
version: 5-5
runtime: python
api_version: 1

default_expiration: "30d"

handlers:

- url: /google75906d613a2a09ba.html
  static_files: static/google75906d613a2a09ba.html
  upload: static/google75906d613a2a09ba.html

- url: /(w{2,3})/tutorials.*(\.html|/)
  script: main.py

# Server appropriate mimetype for certain static content.

- url: /(\w{2,3})/(tutorials/)(casestudies/)?(.*?/)([^/]*\.zip)
  static_files: content/\2\3/\1/\4\5
  mime_type: application/zip
  upload: content/tutorials/(.*\.zip)

- url: /(\w{2,3})/(tutorials/)(casestudies/)?(.*?/)([^/]*\.crx)
  static_files: content/\2\3/\1/\4\5
  mime_type: application/x-chrome-extension
  upload: content/tutorials/(.*\.crx)

- url: /(\w{2,3})/(tutorials/)(casestudies/)?(.*?/)([^/]*\.mp4)
  static_files: content/\2\3/\1/\4\5
  mime_type: video/mp4
  upload: content/tutorials/(.*\.mp4)

- url: /(\w{2,3})/(tutorials/)(casestudies/)?(.*?/)([^/]*\.webm)
  static_files: content/\2\3/\1/\4\5
  mime_type: video/webm
  upload: content/tutorials/(.*\.webm)

- url: /(\w{2,3})/(tutorials/)(casestudies/)?(.*?/)([^/]*\.ogv)
  static_files: content/\2\3/\1/\4\5
  mime_type: video/ogg
  upload: content/tutorials/(.*\.ogv)

#
# Audio Formats
#
- url: /(\w{2,3})/(tutorials/casestudies)/(.+\.(ogg|oga))
  mime_type: audio/ogg
  static_files: content/\2/static/\3
  upload: content/tutorials/(.*\.(ogg|oga))

- url: /(\w{2,3})/(tutorials/[^/]+/[^/]+)/(.+\.(ogg|oga))
  mime_type: audio/ogg
  static_files: content/\2/static/\3
  upload: content/tutorials/(.*\.(ogg|oga))

- url: /(\w{2,3})/(tutorials/casestudies)/(.+\.mp3)
  mime_type: audio/mp3
  static_files: content/\2/static/\3
  upload: content/tutorials/(.*\.mp3)

- url: /(\w{2,3})/(tutorials/[^/]+/[^/]+)/(.+\.mp3)
  mime_type: audio/mp3
  static_files: content/\2/static/\3
  upload: content/tutorials/(.*\.mp3)

#
# Cache Manifests
#
- url: /(\w{2,3})/(tutorials/casestudies)/(.+\.(appcache|manifest))
  expiration: "0s"
  mime_type: text/cache-manifest
  static_files: content/\2/static/\3
  upload: content/tutorials/(.*\.(appcache|manifest))

- url: /(\w{2,3})/(tutorials/[^/]+/[^/]+)/(.+\.(appcache|manifest))
  expiration: "0s"
  mime_type: text/cache-manifest
  static_files: content/\2/static/\3
  upload: content/tutorials/(.*\.(appcache|manifest))

#
# Everything else
#
- url: /(\w{2,3})/(tutorials/casestudies)/(.+\.(gif|swf|mp3|css|js|png|jpeg|jpg|svg|ogm|fla))
  static_files: content/\2/static/\3
  upload: content/tutorials/(.*\.(gif|swf|mp3|css|js|png|jpeg|jpg|svg|ogm|fla))

- url: /(\w{2,3})/(tutorials/[^/]+/[^/]+)/(.+\.(html|gif|swf|mp3|css|js|png|jpeg|jpg|svg|ogm|fla))
  static_files: content/\2/static/\3
  upload: content/tutorials/(.*?/(?!index)[^/]*\.(html|gif|swf|mp3|css|js|png|jpeg|jpg|svg|ogm|fla))

# Anything under /static will automatically be considered static.
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: .*
  script: main.py
