id: ebidelman
name:
  given: Eric
  family: Bidelman
org:
  name: Google
  unit: Developer Relations
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.385981
  lon: -122.083855
homepage: http://www.google.com/profiles/ebidel
google: ebidel
twitter: ebidel
email: e.bidelman@google.com

---

id: mahemoff
name:
  given: Michael
  family: Mahemoff
org:
  name: Google
  unit: Developer Relations
address:
  locality: London
  region: London
  country: UK
  lat: 51.51452
  lon: 0
homepage: http://mahemoff.com
google: mahemoff
twitter: mahemoff
email: mahemoff@google.com

---

id: paulkinlan
name:
  given: Paul
  family: Kinlan
org:
  name: Google
  unit: Developer Relations
address:
  locality: London
  region: London
  country: UK
  lat: 51.51452
  lon: 0
homepage: http://paul.kinlan.me
google: paul.kinlan
twitter: paul_kinlan
email: paul.kinlan@google.com

---

id: sethladd
name:
  given: Seth
  family: Ladd
org:
  name: Google
  unit: Developer Relations
address:
  locality: Mountain View
  region: California
  country: US
  lat: 37.385981
  lon: -122.083855
homepage: http://sethladd.com
google: sethladd
twitter: sethladd
email: sethladd@google.com

---

id: paulirish
name:
  given: Paul
  family: Irish
org:
  name: Google
  unit: Developer Relations
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.385981
  lon: -122.083855
homepage: http://paulirish.com
google: paulirish
twitter: paul_irish
email: paulirish@google.com

---

id: michaeldewey
name:
  given: Mike
  family: Dewey
org:
  name: deviantART
  unit: Muro
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.385981
  lon: -122.083855
homepage: http://paulirish.com
google: paulirish
twitter: paul_irish
email: paulirish@google.com

---

id: davidtong
name:
  given: David
  family: Tong
org:
  name: Box.net
  unit: Box.net
address:
  locality: Palo Alto
  region: California
  country: USA
  lat: 37.385981
  lon: -122.083855
homepage: http://www.davidtong.me
google: davidtwtong
twitter: davidalism
email: davidtwtong@gmail.com

---

id: malteubl
name:
  given: Malte
  family: Ubl
org:
  name: Google
  unit: Customer Solutions Engineering
address:
  locality: Hamburg
  region: 
  country: Malte
  lat: 53.55
  lon: 10.0
homepage: http://nonblocking.io
google: malte.ubl
twitter: cramforce
email: malteubl@google.com

---

id: derekdetweiler
name:
  given: Derek
  family: Detweiler
org:
  name: Gopherwood Studios
  unit: Game Designer
address:
  locality: Hickory
  region: North Carolina
  country: USA
  lat: 35.737778
  lon: -81.328333
homepage: http://gopherwoodstudios.com/
google: http://www.google.com/profiles/derek.detweiler
twitter: gopherwood
email: derek.detweiler@gopherwoodstudios.com

---

id: ernestd
name:
  given: Ernest
  family: Delgado
org:
  name: Google
  unit: Developer Relations
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.385981
  lon: -122.083855
homepage: http://ernestdelgado.com/
google: ernestd
twitter: edr
email: ernestd@google.com


