id: ebidelman
name:
  given: Eric
  family: Bidelman
org:
  name: Google
  unit: Developer Relations
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.42192
  lon: -122.087824
homepage: http://ebidel.com
google: 118075919496626375791
twitter: ebidel
email: e.bidelman@google.com

---

id: mahemoff
name:
  given: Michael
  family: Mahemoff
org:
  name: Google
  unit: Developer Relations
address:
  locality: London
  region: London
  country: UK
  lat: 51.4948
  lon: -0.1467
homepage: http://mahemoff.com
google: mahemoff
twitter: mahemoff
email: mahemoff@google.com
lanyrd: true

---

id: paulkinlan
name:
  given: Paul
  family: Kinlan
org:
  name: Google
  unit: Developer Relations
address:
  locality: London
  region: London
  country: UK
  lat: 51.4948
  lon: -0.1467
homepage: http://paul.kinlan.me
google: paul.kinlan
twitter: paul_kinlan
email: paul.kinlan@google.com
lanyrd: true

---

id: sethladd
name:
  given: Seth
  family: Ladd
org:
  name: Google
  unit: Developer Relations
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.42192
  lon: -122.087824
homepage: http://sethladd.com
google: sethladd
twitter: sethladd
email: sethladd@google.com

---

id: paulirish
name:
  given: Paul
  family: Irish
org:
  name: Google
  unit: Developer Relations
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.42192
  lon: -122.087824
homepage: http://paulirish.com
google: paulirish
twitter: paul_irish
email: paulirish@google.com
lanyrd: true

---

id: michaeldewey
name:
  given: Mike
  family: Dewey
org:
  name: deviantART
  unit: Muro
address:
  locality: Oakland
  region: California
  country: USA
  lat: 37.8043637
  lon: -122.2711137
homepage:
google:
twitter:
email:

---

id: davidtong
name:
  given: David
  family: Tong
org:
  name: Box.net
  unit: Box.net
address:
  locality: Palo Alto
  region: California
  country: USA
  lat: 37.4226547
  lon: -122.1372117
homepage: http://www.davidtong.me
google: davidtwtong
twitter: davidalism
email: davidtwtong@gmail.com

---

id: malteubl
name:
  given: Malte
  family: Ubl
org:
  name: Google
  unit: Customer Solutions Engineering
address:
  locality: Hamburg
  region: Hamburg
  country: Germany
  lat: 53.55
  lon: 10.0
homepage: http://nonblocking.io
google: malte.ubl
twitter: cramforce
email: malteubl@google.com
image: http://a0.twimg.com/profile_images/1151487948/glasses.jpg
lanyrd: true

---

id: derekdetweiler
name:
  given: Derek
  family: Detweiler
org:
  name: Gopherwood Studios
  unit: Game Designer
address:
  locality: Hickory
  region: North Carolina
  country: USA
  lat: 35.737778
  lon: -81.328333
homepage: http://gopherwoodstudios.com/
google: http://www.google.com/profiles/derek.detweiler
twitter: gopherwood
email: derek.detweiler@gopherwoodstudios.com

---

id: ernestd
name:
  given: Ernest
  family: Delgado
org:
  name: Google
  unit: Developer Relations
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.42192
  lon: -122.087824
homepage: http://ernestdelgado.com/
google: ernestd
twitter: edr
email: ernestd@google.com

---

id: danielmoore
name:
 given: Daniel X.
 family: Moore
org:
 name: STRd6
 unit: Pixel Relations
address:
 locality: Sunnyvale
 region: California
 country: USA
 lat:  37.3688889
 lon: -122.0352778
homepage: http://strd6.com
google: 104138221626061560232
twitter: STRd6
email: yahivin@gmail.com

---

id: hakimelhattab
name:
 given: Hakim
 family: El Hattab
org:
 name: Fi
 unit: Senior Interactive Developer
address:
 locality: Stockholm
 region: Stockholm
 country: Sweden
 lat:  59.333386
 lon: 18.075834
homepage: http://hakim.se/experiments
google: hakim.elhattab
twitter: hakimel
email: hakim.elhattab@gmail.com

---

id: jeremychone
name:
  given: Jeremy
  family: Chone
org:
  name: N2N-Apps
  unit: Developer
address:
  locality: San Francisco
  region: California
  country: USA
  lat: 37.775
  lon: -122.4183333
homepage: http://n2napps.com
google: jeremy.chone
twitter: jeremychone
email: jeremy.chone@gmail.com

---

id: matthackett
name:
  given: Matt
  family: Hackett
org:
  name: Lost Decade Games
  unit: Programmer, Designer
address:
  locality: San Jose
  region: California
  country: USA
  lat: 37.3394
  lon: -121.893
homepage: http://www.lostdecadegames.com/
google: http://www.google.com/profiles/richtaur
twitter: richtaur
email: matt@lostdecadegames.com

---

id: geoffblair
name:
  given: Geoff
  family: Blair
org:
  name: Lost Decade Games
  unit: Programmer, Designer
address:
  locality: Sunnyvale
  region: California
  country: USA
  lat: 37.402210
  lon: -122.016089
homepage: http://www.lostdecadegames.com
google: http://www.google.com/profiles/gmblair
twitter: geoffblair
email: geoff@lostdecadegames.com

---

id: mdeal
name:
  given: Michael
  family: Deal
org:
  name: Orange Honey
  unit: New Product Development
address:
  locality: Portland
  region: Oregon
  country: USA
  lat: 45.524381
  lon: -122.683466
homepage: http://mudcu.be/
google: MUDCUBE
twitter: mudcube
email: mudcube@gmail.com

---

id: adammark
name:
  given: Adam
  family: Mark
org:
  name: Pagoda Software
  unit: Programmer, Designer
address:
  locality: Bethesda
  region: Maryland
  country: USA
  lat: 38.982097
  lon: -77.095227
homepage: http://www.adammark.net
google:
twitter:
email: adam.mark@pagodagames.com

---

id: adriangould
name:
  given: Adrian
  family: Gould
org:
  name: Pagoda Software
  unit: Programmer, Designer
address:
  locality: Reston
  region: Virginia
  country: USA
  lat: 38.968721
  lon: -77.341096
homepage: http://pagodagames.com
google:
twitter:
email: adrian.gould@pagodagames.com

---

id: luigimontanez
name:
  given: Luigi
  family: Montanez
org:
  name: Sunlight Labs
  unit: Software Developer
address:
  locality: Washington
  region: DC
  lat: 38.907245
  lon: -77.042317
homepage: http://sunlightlabs.com/
google: luigi.montanez
twitter: LuigiMontanez
email: luigi.montanez@gmail.com

---

id: smus
name:
  given: Boris
  family: Smus
org:
  name: Google
  unit: Developer Relations
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.42192
  lon: -122.087824
homepage: http://smus.com
google: boris.smus
twitter: borismus
email: smus@google.com

---

id: petele
name:
  given: Pete
  family: LePage
org:
  name: Google
  unit: Developer Relations
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.42192
  lon: -122.087824
homepage: http://petelepage.com
google:
twitter: petele
email: petele@google.com

---

id: ilmari
name:
  given: Ilmari
  family: Heikkinen
org:
  name: Google
  unit: Developer Relations
address:
  locality: London
  region: London
  country: UK
  lat: 51.50722
  lon: -0.1275
homepage: http://fhtr.org
google: ilmari
twitter: ilmarihei
email: ilmari@google.com

---

id: jankleinert
name:
  given: Jan
  family: Kleinert
org:
  name: Google
  unit: Developer Relations
address:
  locality: New York
  region: New York
  country: USA
  lat: 40.740914
  lon: -74.002032
homepage: http://jankleinert.com
google: jankleinert
twitter: jankleinert
email: jkleinert@google.com

---
    
id: paullewis
name:
  given: Paul
  family: Lewis
org:
  name: Aerotwist
  unit: Developer
address:
  locality: Stockholm
  region: Stockholm
  country: Sweden
  lat: 59.333189
  lon: 18.06427
homepage: http://aerotwist.com
twitter: aerotwist
email: website@aerotwist.com

---
    
id: eligrey
name:
  given: Eli
  family: Grey
org:
  name: ΩF:∅
  unit: Programmer
address:
  locality: Pennsylvania
  region: Pennsylvania
  country: USA
  lat: 40.8666
  lon: -77.8
homepage: http://eligrey.com/blog/
twitter: sephr
email: me@eligrey.com

---

id: taligarsiel
name:
  given: Tali
  family: Garsiel
org:
  name: Incapsula
  unit: Developer 
address:
  locality: 
  region: 
  country: Israel
  lat: 31.5
  lon: 34.75
homepage: http://taligarsiel.com/
email: tgarsiel@gmail.com

---

id: agektmr
name:
  given: Eiji
  family: Kitamura
org:
  name: Google
  unit: Developer Relations
address:
  locality: Tokyo
  region: 
  country: Japan
  lat: 35.666
  lon: 139.766666667
homepage: 
google: agektmr
twitter: agektmr
email: agektmr@google.com

---

id: dutton
name:
  given: Sam
  family: Dutton
org:
  name: Google
  unit: Developer Relations
address:
  locality: London
  region: England
  country: United Kingdom
  lat: 51.4948
  lon: -0.1467
homepage: http://samdutton.wordpress.com
google: dutton
twitter: sw12
email: dutton@google.com
lanyrd: true

---

id: jameswilliams
name:
  given: James
  family: Williams
org:
  name: Independent
  unit: Developer
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.4194
  lon: -122.0906
homepage: http://jameswilliams.be
google: james.l.williams
twitter: ecspike
email: james.l.williams@gmail.com
lanyrd: true

---

id: wesleyhales
name:
  given: Wesley
  family: Hales
org:
  name: Red Hat
  unit: Senior Developer
address:
  locality: Atlanta
  region: Georgia
  country: USA
  lat: 33.845701 
  lon: -84.369196 
homepage: http://wesleyhales.com
google: wesleyhales
twitter: wesleyhales
email: wesleyhales@gmail.com
lanyrd: true

---

id: monsurhossain
name:
  given: Monsur
  family: Hossain
org:
  name: Google
  unit: Software Engineer
address:
  locality: Chicago
  region: Illinois
  country: USA
  lat: 41.877866
  lon: -87.629669
homepage: http://monsur.hossa.in
google: 113897230587820705070
twitter: monsur
email: monsur@gmail.com

---

id: idog
name:
  given: Ido
  family: Green
org:
  name: Google
  unit: Developer Relations
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.42192
  lon: -122.087824
homepage: http://greenido.wordpress.com
google: 101709676645745930035
twitter: greenido
email: idog@google.com

---

id: marcinwichary
name:
  given: Marcin
  family: Wichary
org:
  name: Google
  unit: Sr. User Experience Designer
address:
  locality: Mountain View
  region: California
  country: USA
  lat: 37.42192
  lon: -122.087824
homepage: http://www.aresluna.org/
google: 101765089097091765365
twitter: mwichary
email: mwichary@gmail.com
